using System.Collections.Generic;
using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;

namespace Asm.Domain.SourceGenerators;

/// <summary>
/// Generates the implementation of properties marked with <c>[Navigation]</c>.
/// </summary>
[Generator(LanguageNames.CSharp)]
public sealed class NavigationGenerator : IIncrementalGenerator
{
    private const string AttributeMetadataName = "Asm.Domain.NavigationAttribute";

    /// <inheritdoc />
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var navigations = context.SyntaxProvider.ForAttributeWithMetadataName(
            AttributeMetadataName,
            static (node, _) => node is PropertyDeclarationSyntax,
            static (attributeContext, _) => Analyse(attributeContext));

        context.RegisterSourceOutput(navigations, static (context, navigation) =>
        {
            if (navigation.Diagnostic is { } diagnostic)
            {
                context.ReportDiagnostic(diagnostic.ToDiagnostic());
            }

            if (navigation.HintName is not null && navigation.Source is not null)
            {
                context.AddSource(navigation.HintName, SourceText.From(navigation.Source, Encoding.UTF8));
            }
        });
    }

    private static Result Analyse(GeneratorAttributeSyntaxContext context)
    {
        var property = (IPropertySymbol)context.TargetSymbol;
        var declaration = (PropertyDeclarationSyntax)context.TargetNode;
        var owner = property.ContainingType;

        if (!declaration.Modifiers.Any(SyntaxKind.PartialKeyword))
        {
            return Result.Failed(Diagnostics.PropertyMustBePartial, declaration.Identifier, property.Name);
        }

        var unsealedType = Nesting(owner).FirstOrDefault(type => !IsPartial(type));
        if (unsealedType is not null)
        {
            return Result.Failed(Diagnostics.ContainingTypeMustBePartial, declaration.Identifier, unsealedType.Name, property.Name);
        }

        if (property.Type.IsValueType || property.Type.NullableAnnotation == NullableAnnotation.Annotated)
        {
            return Result.Failed(Diagnostics.PropertyMustBeNonNullableReference, declaration.Identifier, property.Name);
        }

        if (property.GetMethod is null)
        {
            return Result.Failed(Diagnostics.PropertyMustHaveGetter, declaration.Identifier, property.Name);
        }

        if (property.SetMethod is null)
        {
            return Result.Failed(Diagnostics.PropertyMustHaveSetter, declaration.Identifier, property.Name);
        }

        if (property.PartialImplementationPart is not null)
        {
            return Result.Failed(Diagnostics.PropertyAlreadyImplemented, declaration.Identifier, property.Name);
        }

        return Result.Generated(HintName(owner, property), Emit(owner, property, declaration));
    }

    private static string Emit(INamedTypeSymbol owner, IPropertySymbol property, PropertyDeclarationSyntax declaration)
    {
        var builder = new StringBuilder();
        builder.AppendLine("// <auto-generated/>");
        builder.AppendLine("#nullable enable");
        builder.AppendLine();

        var indent = string.Empty;

        if (!owner.ContainingNamespace.IsGlobalNamespace)
        {
            builder.Append("namespace ").AppendLine(owner.ContainingNamespace.ToDisplayString());
            builder.AppendLine("{");
            indent = "    ";
        }

        var nesting = Nesting(owner).Reverse().ToArray();
        foreach (var type in nesting)
        {
            builder.Append(indent).Append("partial ").AppendLine(Declaration(type));

            foreach (var constraint in Constraints(type))
            {
                builder.Append(indent).Append("    ").AppendLine(constraint);
            }

            builder.Append(indent).AppendLine("{");
            indent += "    ";
        }

        var type_ = property.Type.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
        var modifiers = string.Join(" ", declaration.Modifiers.Select(modifier => modifier.Text));
        var message = $"Navigation property '{owner.Name}.{property.Name}' has not been loaded. Include it in the query that loaded this entity.";

        // `field` rather than a named backing field: a derived name can collide with a field the
        // entity already has, or with another navigation whose name differs only in its first
        // letter's case, and the consumer gets CS0102 out of generated code they did not write.
        // It lowers to the same <Name>k__BackingField an auto-property produces, so EF Core's
        // backing-field convention still writes straight to it and the throwing getter never fires
        // on a loaded entity.
        builder.Append(indent).Append(modifiers).Append(' ').Append(type_).Append(' ').AppendLine(property.Name);
        builder.Append(indent).AppendLine("{");
        builder.Append(indent).Append("    get => field ?? throw new global::System.InvalidOperationException(\"").Append(message).AppendLine("\");");
        builder.Append(indent).AppendLine("    set => field = value;");
        builder.Append(indent).AppendLine("}");

        foreach (var _ in nesting)
        {
            indent = indent.Substring(4);
            builder.Append(indent).AppendLine("}");
        }

        if (!owner.ContainingNamespace.IsGlobalNamespace)
        {
            builder.AppendLine("}");
        }

        return builder.ToString();
    }

    private static IEnumerable<INamedTypeSymbol> Nesting(INamedTypeSymbol type)
    {
        for (var current = type; current is not null; current = current.ContainingType)
        {
            yield return current;
        }
    }

    private static bool IsPartial(INamedTypeSymbol type) =>
        type.DeclaringSyntaxReferences.Any(reference =>
            reference.GetSyntax() is TypeDeclarationSyntax syntax && syntax.Modifiers.Any(SyntaxKind.PartialKeyword));

    private static string Declaration(INamedTypeSymbol type)
    {
        var keyword = type switch
        {
            { IsRecord: true, TypeKind: TypeKind.Struct } => "record struct",
            { IsRecord: true } => "record",
            { TypeKind: TypeKind.Struct } => "struct",
            { TypeKind: TypeKind.Interface } => "interface",
            _ => "class",
        };

        var name = type.TypeParameters.Length == 0
            ? type.Name
            : $"{type.Name}<{string.Join(", ", type.TypeParameters.Select(parameter => parameter.Name))}>";

        return $"{keyword} {name}";
    }


    /// <summary>
    /// The `where` clauses for a type's own type parameters.
    /// </summary>
    /// <remarks>
    /// A partial declaration has to repeat them: omitted, the compiler reports CS0265 for
    /// inconsistent constraints and no generic entity can carry a navigation.
    /// </remarks>
    private static IEnumerable<string> Constraints(INamedTypeSymbol type)
    {
        foreach (var parameter in type.TypeParameters)
        {
            var constraints = new List<string>();

            if (parameter.HasReferenceTypeConstraint)
            {
                constraints.Add(parameter.ReferenceTypeConstraintNullableAnnotation == NullableAnnotation.Annotated ? "class?" : "class");
            }

            if (parameter.HasUnmanagedTypeConstraint)
            {
                constraints.Add("unmanaged");
            }
            else if (parameter.HasValueTypeConstraint)
            {
                constraints.Add("struct");
            }

            if (parameter.HasNotNullConstraint)
            {
                constraints.Add("notnull");
            }

            constraints.AddRange(parameter.ConstraintTypes.Select(constraint => constraint.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat)));

            // struct already implies a parameterless constructor, and the pair is not legal together.
            if (parameter.HasConstructorConstraint && !parameter.HasValueTypeConstraint && !parameter.HasUnmanagedTypeConstraint)
            {
                constraints.Add("new()");
            }

            if (constraints.Count > 0)
            {
                yield return $"where {parameter.Name} : {string.Join(", ", constraints)}";
            }
        }
    }

    private static string HintName(INamedTypeSymbol owner, IPropertySymbol property)
    {
        var qualified = owner.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat.WithGlobalNamespaceStyle(SymbolDisplayGlobalNamespaceStyle.Omitted));
        var identity = qualified + "." + property.Name;

        var builder = new StringBuilder(identity.Length + 16);
        foreach (var character in qualified)
        {
            builder.Append(char.IsLetterOrDigit(character) || character == '.' || character == '_' ? character : '_');
        }

        // Flattening is lossy: Account<T> and a type legally named Account_T_ both come out as
        // Account_T_. Two such entities in one compilation would hand the driver duplicate hint
        // names and fail the build, so the identity's hash goes on the end to tell them apart.
        return builder.Append('.').Append(property.Name)
                      .Append('.').Append(Hash(identity))
                      .Append(".g.cs").ToString();
    }

    /// <summary>
    /// FNV-1a, for a hint-name suffix. Stable across runs, which a generator's output must be.
    /// </summary>
    private static string Hash(string value)
    {
        unchecked
        {
            var hash = 2166136261;

            foreach (var character in value)
            {
                hash = (hash ^ character) * 16777619;
            }

            return hash.ToString("x8");
        }
    }
}
