using System.Collections.Generic;
using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;

namespace Asm.Domain.SourceGenerators;

/// <summary>
/// Generates the implementation of properties marked with <c>[Navigation]</c>.
/// </summary>
[Generator(LanguageNames.CSharp)]
public sealed class NavigationGenerator : IIncrementalGenerator
{
    private const string AttributeMetadataName = "Asm.Domain.NavigationAttribute";

    /// <inheritdoc />
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var navigations = context.SyntaxProvider.ForAttributeWithMetadataName(
            AttributeMetadataName,
            static (node, _) => node is PropertyDeclarationSyntax,
            static (attributeContext, _) => Analyse(attributeContext));

        context.RegisterSourceOutput(navigations, static (context, navigation) =>
        {
            if (navigation.Diagnostic is { } diagnostic)
            {
                context.ReportDiagnostic(diagnostic.ToDiagnostic());
            }

            if (navigation.HintName is not null && navigation.Source is not null)
            {
                context.AddSource(navigation.HintName, SourceText.From(navigation.Source, Encoding.UTF8));
            }
        });
    }

    private static Result Analyse(GeneratorAttributeSyntaxContext context)
    {
        var property = (IPropertySymbol)context.TargetSymbol;
        var declaration = (PropertyDeclarationSyntax)context.TargetNode;
        var owner = property.ContainingType;

        if (!declaration.Modifiers.Any(SyntaxKind.PartialKeyword))
        {
            return Result.Failed(Diagnostics.PropertyMustBePartial, declaration.Identifier, property.Name);
        }

        var unsealedType = Nesting(owner).FirstOrDefault(type => !IsPartial(type));
        if (unsealedType is not null)
        {
            return Result.Failed(Diagnostics.ContainingTypeMustBePartial, declaration.Identifier, unsealedType.Name, property.Name);
        }

        if (property.Type.IsValueType || property.Type.NullableAnnotation == NullableAnnotation.Annotated)
        {
            return Result.Failed(Diagnostics.PropertyMustBeNonNullableReference, declaration.Identifier, property.Name);
        }

        if (property.SetMethod is null)
        {
            return Result.Failed(Diagnostics.PropertyMustHaveSetter, declaration.Identifier, property.Name);
        }

        if (property.PartialImplementationPart is not null)
        {
            return Result.Failed(Diagnostics.PropertyAlreadyImplemented, declaration.Identifier, property.Name);
        }

        return Result.Generated(HintName(owner, property), Emit(owner, property, declaration));
    }

    private static string Emit(INamedTypeSymbol owner, IPropertySymbol property, PropertyDeclarationSyntax declaration)
    {
        var builder = new StringBuilder();
        builder.AppendLine("// <auto-generated/>");
        builder.AppendLine("#nullable enable");
        builder.AppendLine();

        var indent = string.Empty;

        if (!owner.ContainingNamespace.IsGlobalNamespace)
        {
            builder.Append("namespace ").AppendLine(owner.ContainingNamespace.ToDisplayString());
            builder.AppendLine("{");
            indent = "    ";
        }

        var nesting = Nesting(owner).Reverse().ToArray();
        foreach (var type in nesting)
        {
            builder.Append(indent).Append("partial ").AppendLine(Declaration(type));
            builder.Append(indent).AppendLine("{");
            indent += "    ";
        }

        var type_ = property.Type.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
        var field = BackingFieldName(property.Name);
        var modifiers = string.Join(" ", declaration.Modifiers.Select(modifier => modifier.Text));
        var message = $"Navigation property '{owner.Name}.{property.Name}' has not been loaded. Include it in the query that loaded this entity.";

        builder.Append(indent).Append("private ").Append(type_).Append("? ").Append(field).AppendLine(";");
        builder.AppendLine();
        builder.Append(indent).Append(modifiers).Append(' ').Append(type_).Append(' ').AppendLine(property.Name);
        builder.Append(indent).AppendLine("{");
        builder.Append(indent).Append("    get => ").Append(field)
               .Append(" ?? throw new global::System.InvalidOperationException(\"").Append(message).AppendLine("\");");
        builder.Append(indent).Append("    set => ").Append(field).AppendLine(" = value;");
        builder.Append(indent).AppendLine("}");

        foreach (var _ in nesting)
        {
            indent = indent.Substring(4);
            builder.Append(indent).AppendLine("}");
        }

        if (!owner.ContainingNamespace.IsGlobalNamespace)
        {
            builder.AppendLine("}");
        }

        return builder.ToString();
    }

    private static IEnumerable<INamedTypeSymbol> Nesting(INamedTypeSymbol type)
    {
        for (var current = type; current is not null; current = current.ContainingType)
        {
            yield return current;
        }
    }

    private static bool IsPartial(INamedTypeSymbol type) =>
        type.DeclaringSyntaxReferences.Any(reference =>
            reference.GetSyntax() is TypeDeclarationSyntax syntax && syntax.Modifiers.Any(SyntaxKind.PartialKeyword));

    private static string Declaration(INamedTypeSymbol type)
    {
        var keyword = type switch
        {
            { IsRecord: true, TypeKind: TypeKind.Struct } => "record struct",
            { IsRecord: true } => "record",
            { TypeKind: TypeKind.Struct } => "struct",
            { TypeKind: TypeKind.Interface } => "interface",
            _ => "class",
        };

        var name = type.TypeParameters.Length == 0
            ? type.Name
            : $"{type.Name}<{string.Join(", ", type.TypeParameters.Select(parameter => parameter.Name))}>";

        return $"{keyword} {name}";
    }

    private static string BackingFieldName(string propertyName) =>
        "_" + char.ToLowerInvariant(propertyName[0]) + propertyName.Substring(1);

    private static string HintName(INamedTypeSymbol owner, IPropertySymbol property)
    {
        var qualified = owner.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat.WithGlobalNamespaceStyle(SymbolDisplayGlobalNamespaceStyle.Omitted));

        var builder = new StringBuilder(qualified.Length + property.Name.Length + 6);
        foreach (var character in qualified)
        {
            builder.Append(char.IsLetterOrDigit(character) || character == '.' || character == '_' ? character : '_');
        }

        return builder.Append('.').Append(property.Name).Append(".g.cs").ToString();
    }
}
