<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <CoverletInclude>[Asm.Hosting]*</CoverletInclude>
    <CoverletExcludeByFile>**/*</CoverletExcludeByFile>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\Asm.Hosting\Asm.Hosting.csproj" />
  </ItemGroup>

</Project>
