<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <CoverletInclude>[Asm.Domain]*</CoverletInclude>
    <CoverletExcludeByFile>**/*</CoverletExcludeByFile> 
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Reqnroll.xUnit.v3" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\Asm.Domain\Asm.Domain.csproj" />
    <ProjectReference Include="..\..\src\Asm.Reqnroll\Asm.Reqnroll.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Using Include="Asm.Reqnroll" />
    <Using Include="Reqnroll" />
  </ItemGroup>

  <ItemGroup>
    <None Update="reqnroll.json">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
  </ItemGroup>

</Project>
