<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <CoverletInclude>[Asm.Umbraco]*</CoverletInclude>
    <CoverletExcludeByFile>**/*</CoverletExcludeByFile>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Moq" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\Asm.Umbraco\Asm.Umbraco.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Using Include="Moq" />
  </ItemGroup>

</Project>
