<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <CoverletInclude>[Asm.Testing.Domain]*</CoverletInclude>
    <CoverletExcludeByFile>**/*</CoverletExcludeByFile>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\Asm.Testing.Domain\Asm.Testing.Domain.csproj" />
  </ItemGroup>

</Project>
